env:
  browser: true
  es6: true
  node: true

ignorePatterns:
  - dist
  - out
  - template
  - "packages/**/wasm/*.js"
  - "!.storybook"
  - storybook-static

plugins:
  - file-progress
  - tss-unused-classes

extends:
  - plugin:@foxglove/base
  - plugin:@foxglove/react
  - plugin:@foxglove/jest

settings:
  import/internal-regex: "^@foxglove"

rules:
  "@foxglove/license-header": error

  tss-unused-classes/unused-classes: error

  # show progress while linting
  file-progress/activate: warn

  # enabled in .eslintrc.ci.yaml
  prettier/prettier: off
  import/no-self-import: off
  import/no-duplicates: off

  id-denylist:
    - error
    - useEffectOnce
    - window # don't allow redefining window
  no-console: off # configured in no-restricted-syntax

  react/jsx-uses-react: off
  react/prop-types: off # Unnecessary with typescript validation
  react-hooks/exhaustive-deps:
    - error
    - additionalHooks: "(useAsync(?!AppConfigurationValue))|useCallbackWithToast"
  react/jsx-curly-brace-presence: [error, never]

  # The _sx_ property is slow
  # https://stackoverflow.com/questions/68383046/is-there-a-performance-difference-between-the-sx-prop-and-the-makestyles-function
  react/forbid-component-props:
    - error
    - forbid:
        - propName: "sx"
          message: "Use of the sx prop is not advised due to performance issues. Consider using alternative styling methods instead."

  no-warning-comments:
    - error
    - terms: ["fixme", "xxx", "todo"]
      location: anywhere

  no-restricted-imports:
    - error
    - paths:
        - name: "@mui/material"
          importNames: [styled]
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@mui/material/styles/styled"
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@emotion/styled"
          message: "@emotion/styled has performance implications. Use tss-react/mui instead."

        - name: "lodash"
          importNames: [get]
          message: "Use optional chaining instead of lodash.get."
        - name: "lodash/get"
          message: "Use optional chaining instead of lodash.get."

  no-restricted-syntax:
    - error
    - selector: "MethodDefinition[kind='get'], Property[kind='get']"
      message: "Property getters are not allowed; prefer function syntax instead."
    - selector: "MethodDefinition[kind='set'], Property[kind='set']"
      message: "Property setters are not allowed; prefer function syntax instead."

    # We disable console methods here rather than using no-console so that it doesn't prohibit overrides such as "console.info = ..."
    - selector: "CallExpression[callee.object.name='console'][callee.property.name!=/^(warn|error|debug|assert)$/]"
      message: "Unexpected property on console object was called"

    - selector: "TSNullKeyword, Literal[raw=null]"
      message: >
        Prefer undefined instead of null. When required for React refs/components, use
        the `ReactNull` alias. Otherwise, if strictly necessary, disable this error with
        `// eslint-disable-next-line no-restricted-syntax`. For rationale, see:
        https://github.com/sindresorhus/meta/discussions/7"

  jest/expect-expect:
    [error, { assertFunctionNames: [expect*, sendNotification.expectCalledDuringTest] }]

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: ./tsconfig.eslint.json
    rules:
      "@typescript-eslint/ban-ts-comment":
        - error
        - ts-expect-error: allow-with-description

      "@typescript-eslint/explicit-member-accessibility": error

      "@typescript-eslint/no-inferrable-types": off # It's sometimes useful to explicitly name to guard against future changes
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/no-implied-eval": off # We need to use `new Function()`

      # These are related to `any` types, which we generally don't have except from imports
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-return": off
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-unsafe-call": off

      "@typescript-eslint/require-await": off # Async functions without await are used to satisfy interface requirements

      # These could theoretically be turned on (or merit investigation) but are currently noisy
      "@typescript-eslint/no-misused-promises": off # Often used with e.g. useCallback(async () => {})
      "@typescript-eslint/restrict-template-expressions": off

      "@typescript-eslint/prefer-regexp-exec": off
      "@typescript-eslint/no-unnecessary-condition": error
      "@typescript-eslint/unbound-method": [error, { ignoreStatic: true }]

  - rules:
      "@typescript-eslint/no-explicit-any": off
    files:
      - "**/*.stories.tsx"
      - "**/*.test.tsx"
      - "**/*.test.ts"

  - rules:
      react/forbid-component-props: off
    files:
      - "**/*.stories.tsx"

  - rules:
      no-restricted-imports: off
    files:
      # Ignore existing implementations of @mui/styled
      - "web/src/VersionBanner.tsx"
      - "packages/studio-base/src/components/DataSourceSidebar/DataSourceSidebar.tsx"
      - "packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx"
      - "packages/studio-base/src/components/EmptyPanelLayout.tsx"
      - "packages/studio-base/src/components/EmptyState.tsx"
      - "packages/studio-base/src/components/ExpandingToolbar.tsx"
      - "packages/studio-base/src/components/ExtensionDetails.tsx"
      - "packages/studio-base/src/components/ExtensionsSettings/index.tsx"
      - "packages/studio-base/src/components/LayoutBrowser/LayoutRow.tsx"
      - "packages/studio-base/src/components/LayoutBrowser/SignInPrompt.tsx"
      - "packages/studio-base/src/components/OpenDialog/OpenDialog.tsx"
      - "packages/studio-base/src/components/OpenDialog/Start.tsx"
      - "packages/studio-base/src/components/OpenDialog/View.tsx"
      - "packages/studio-base/src/components/Panel.tsx"
      - "packages/studio-base/src/components/PanelLayout.tsx"
      - "packages/studio-base/src/components/PanelToolbar/ToolbarIconButton.tsx"
      - "packages/studio-base/src/components/PanelToolbar/index.tsx"
      - "packages/studio-base/src/components/PlaybackControls/PlaybackTimeDisplayMethod.tsx"
      - "packages/studio-base/src/components/PlaybackControls/Slider.stories.tsx"
      - "packages/studio-base/src/components/PlaybackSpeedControls.tsx"
      - "packages/studio-base/src/components/SettingsTreeEditor/VisibilityToggle.tsx"
      - "packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorScalePicker.tsx"
      - "packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx"
      - "packages/studio-base/src/components/ShareJsonModal.tsx"
      - "packages/studio-base/src/components/TextHighlight.tsx"
      - "packages/studio-base/src/panels/Image/components/Toolbar.tsx"
      - "packages/studio-base/src/panels/Image/components/ZoomMenu.tsx"
      - "packages/studio-base/src/panels/Image/ImageView.tsx"
      - "packages/studio-base/src/panels/NodePlayground/BottomBar/DiagnosticsSection.tsx"
      - "packages/studio-base/src/panels/NodePlayground/BottomBar/index.tsx"
      - "packages/studio-base/src/panels/NodePlayground/Sidebar.tsx"
      - "packages/studio-base/src/panels/NodePlayground/index.tsx"
      - "packages/studio-base/src/panels/Plot/PathSettingsModal.tsx"
      - "packages/studio-base/src/panels/Publish/index.tsx"
      - "packages/studio-base/src/panels/RawMessages/DiffSpan.tsx"
      - "packages/studio-base/src/panels/Tab/TabbedToolbar.tsx"
      - "packages/studio-base/src/panels/Tab/ToolbarTab.tsx"
      - "packages/studio-base/src/panels/Tab/index.tsx"
      - "packages/studio-base/src/panels/Table/Table.tsx"
      - "packages/studio-base/src/panels/Table/TableCell.tsx"
      - "packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx"
      - "packages/studio-base/src/panels/diagnostics/DiagnosticSummary.tsx"
      - "packages/studio-base/src/stories/storyHelpers.tsx"
