rules:
  # Re-enable these when https://github.com/benmosher/eslint-plugin-import/issues/1996 is fixed
  import/no-unresolved: off
  import/namespace: off
  import/default: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off
