name: Audit

on:
  push:
    branches: [develop, main]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # Run each command in parallel with the same setup steps.
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        config:
          # Specify names so that the GitHub branch protection settings for
          # required checks don't need to change if we ever change the commands used.
          - name: npm audit
            command: yarn npm audit --all --recursive --severity moderate

    name: ${{ matrix.config.name }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: corepack enable yarn

      - name: Restore cache
        uses: actions/cache@v6
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - run: ${{ matrix.config.command }}
