name: Enforce branch naming for main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ ! "${GITHUB_HEAD_REF}" =~ ^(release/|hotfix/) ]]; then
            echo "Source branch must start with 'release/' or 'hotfix/'"
            exit 1
          fi
