name: SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17

      - name: Enable corepack
        run: corepack enable yarn

      - name: Install dependencies
        run: yarn install

      - name: Generates lint report and file path formatting
        run: |
          yarn lint:ci:report
          sed -i 's|/home/runner/work/lichtblick/lichtblick/|./|g' eslint-report.json
        continue-on-error: true

      - name: Test and coverage
        run: yarn test:coverage
        continue-on-error: true

      - name: ScanCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
